version: '3'

services:

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - PROMETHEUS:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.size=256MB'
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
        
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    command:
      - '--path.rootfs=/host'
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  grafana:
    image: grafana/grafana-enterprise
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - GRAFANA:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: "false"
      GF_INSTALL_PLUGINS: grafana-piechart-panel
    restart: unless-stopped
    logging:
      options:
        max-size: "10m"
        max-file: "3"
        
volumes:
    PROMETHEUS:
    GRAFANA:
