version: '3'

services:
  traefik:
    image: traefik:v2.10
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/traefik.toml:/etc/traefik/traefik.toml
    restart: always

  home:
    build: 
      context: jiechen.dev
    labels:
      - traefik.enable=true
      - traefik.http.routers.home.rule=PathPrefix(`/`)
    restart: always
    depends_on:
      - traefik
