[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[entryPoints]
  [entryPoints.web]
    address = ":80"

[log]
  level = "INFO"
  format = "common"
  filePath = "os.stdout"

[accessLog]
  format = "common"
  filePath = "os.stdout"

[api]
  dashboard = true
  insecure = true

[providers.docker]
  exposedByDefault = false