[global]
  checkNewVersion = true
  sendAnonymousUsage = true

[entryPoints]
  [entryPoints.web]
    address = ":80"
  [entryPoints.metrics]
    address = ":8082"

[log]
  level = "INFO"
  format = "common"
  #filePath = "/var/log/traefik.log"

[accessLog]
  filePath = "/var/log/access.log"
  format = "json"

  [accessLog.fields]
    defaultMode = "keep"

    [accessLog.fields.headers]
      defaultMode = "keep"

      [accessLog.fields.headers.names]
        "Cf-connecting-ip" = "keep"
  
[api]
  dashboard = true
  insecure = true

[providers.docker]
  exposedByDefault = false

[metrics]
  [metrics.prometheus]
    entryPoint = "metrics"
    addServicesLabels = true
